export const OFFTO_GETTER_FAQS = "OFFTO_GETTER_FAQS";
export const OFFTO_GETTER_FAQS_Packages = "OFFTO_GETTER_FAQS_Packages";
export const OFFTO_GETTER_TERMS = "OFFTO_GETTER_TERMS";
export const OFFTO_GETTER_ABOUT = "OFFTO_GETTER_ABOUT";
export const OFFTO_GETTER_CONTACT = "OFFTO_GETTER_CONTACT";
